t3: 1.0
#####################################
# カスタム機能定義
#####################################
info:
  name: rdb
  customPackage: com.epion_t3.rdb
  summary:
    - lang: ja_JP
      contents: "RDB（Relational DataBase）関連のコマンドを提供します。"
  description:
    - lang: ja_JP
      contents: "RDB（Relational DataBase）関連のコマンドを提供します。"
#####################################
# コマンド定義
#####################################
commands:
  ##########################
  # ImportRdbData
  ##########################
  - id: ImportRdbData
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: "RDBに対してデータの挿入（インポート）を行います。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: RDB「${rdbConnectConfigRef}」に対して「${value}」をインポートします。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "RDBに対してデータのインポートを行います。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "XMLで定義したデータのインポートが行えます。（DBUnit）"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "Excelで定義したデータのインポートが行えます。（DBUnit）"
      - order: 4
        summary:
          - lang: ja_JP
            contents: "DBUnitで定義されているDataBaseOperationが利用可能です。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「ImportRdbData」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: rdbConnectConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "RDBに対する接続先定義の参照ID # (1)"
        description:
          - lang: ja_JP
            contents: "RDBへの接続先の設定を行っている `Configuration` の参照IDを指定します。"
      - order: 6
        name: dataSetType
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "(xml|excel) # (2)"
        description:
          - lang: ja_JP
            contents: "DataSetの種類を指定します。DataSetとは、RDBのデータ構造を表したもので、DataSetには、CSV、XML、Excelの形式が選べます。本コマンドが利用するDataSetとはすべてDBUnitのDataSetを指します。現状では、CSVには対応ができておりません。"
      - order: 7
        name: operation
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "(insert|clean_insert|update|refresh) # (3)"
        description:
          - lang: ja_JP
            contents: "DataSetをインポートする際のロジックを指定します。Operationの詳細はJUnitのページを参照してください。"
      - order: 8
        name: bind
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "変数バインドを行うかどうかのフラグ # (4)"
        description:
          - lang: ja_JP
            contents: "DataSetの中にVariableを利用するような変数参照が存在する場合に、バインドを行うかを指定できます。"
      - order: 9
        name: value
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "インポートするDataSetのパス（相対） # (5)"
        description:
          - lang: ja_JP
            contents: "インポートするDataSetのファイルのパスを相対パスで指定します。相対パスの基準ディレクトリは対象のシナリオファイルが配置している場所となります。 対象のシナリオファイルはパーツ定義に配置している場合はパーツのYAMLが配置している場所を指します。"
  ##########################
  # ExportRdbData
  ##########################
  - id: ExportRdbData
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: "RDBのデータを抽出（エクスポート）します。エクスポートしたデータはエビデンスとしても保存可能になります。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: レスポンスBodyのJSONからJSONPath表記で「${jsonPath}」から値を取得し、変数「${value}」へ設定する。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "RDBのデータを抽出（エクスポート）します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "XMLで定義されたデータのエクスポートが行えます。（DBUnit）"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "Excelで定義されたデータのエクスポートが行えます。（DBUnit）"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「ExportRdbData」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: rdbConnectConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "RDBに対する接続先定義の参照ID # (1)"
        description:
          - lang: ja_JP
            contents: "RDBへの接続先の設定を行っている `Configuration` の参照IDを指定します。"
      - order: 6
        name: dataSetType
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "(xml|excel) # (2)"
        description:
          - lang: ja_JP
            contents: "DataSetの種類を指定します。DataSetとは、RDBのデータ構造を表したもので、DataSetには、CSV、XML、Excelの形式が選べます。本コマンドが利用するDataSetとはすべてDBUnitのDataSetを指します。現状では、CSVには対応ができておりません。"
      - order: 7
        name: tables
        required: true
        type: array
        summary:
          - lang: ja_JP
            contents: "エクスポート対象のテーブルを定義 # (3)"
        description:
          - lang: ja_JP
            contents: "エクスポートを行う対象のテーブルについて細かく指定が行えます。"
        property:
          - order: 1
            name: table
            required: true
            type: string
            summary:
              - lang: ja_JP
                contents: "対象のテーブル名（物理名）を指定"
          - order: 2
            name: query
            required: true
            type: string
            summary:
              - lang: ja_JP
                contents: "対象のテーブルからデータを抽出するためのクエリー（SQL）を指定"
  ##########################
  # ExecuteRdbScript
  ##########################
  - id: ExecuteRdbScript
    summary:
      - lang: ja_JP
        contents: "RDBに対してスクリプト（SQL）を実行します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "RDB「${rdbConnectConfigRef}」に対して「${value}」を実行します。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "RDBに対してスクリプト（SQL）を実行します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "スクリプト（SQL）へETTTの変数バインドが可能です。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "スクリプト（SQL）はUTF-8で読み込みます。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「ExecuteRdbScript」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: rdbConnectConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "RDBに対する接続先定義の参照ID # (1)"
        description:
          - lang: ja_JP
            contents: "RDBへの接続先の設定を行っている `Configuration` の参照IDを指定します。"
      - order: 6
        name: value
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "スクリプト（SQL）のパス（相対パス）"
  ##########################
  # ExecuteRdbQuery
  ##########################
  - id: ExecuteRdbQuery
    summary:
      - lang: ja_JP
        contents: "RDBに対してクエリー（SQL）を実行します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "RDB「${rdbConnectConfigRef}」に対して「${value}」を実行します。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "RDBに対してクエリー（SQL）を実行します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "クエリー（SQL）へETTTの変数バインドが可能です。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「ExecuteRdbQuery」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: rdbConnectConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "RDBに対する接続先定義の参照ID # (1)"
        description:
          - lang: ja_JP
            contents: "RDBへの接続先の設定を行っている `Configuration` の参照IDを指定します。"
      - order: 6
        name: value
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "クエリー（SQL）のパス（相対パス）"
  ##########################
  # AssertRdbData
  ##########################
  - id: AssertRdbData
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: "RDBのレコードの確認を行います。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: レスポンスBodyのJSONからJSONPath表記で「${jsonPath}」から値を取得し、変数「${value}」へ設定する。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "RDBのレコードの確認を行います。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "期待値はデータセット（DBUnit）で表します。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "結果値は事前にエビデンスとしてエクスポート系のコマンドを利用して取得しておく必要があります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AssertRdbData」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: expectedDataSetPath
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "期待値データセット相対パス # (1)"
        description:
          - lang: ja_JP
            contents: "期待値を定義したデータセットへの相対パス。このコマンドが配置されている場所からの相対パスになります。"
      - order: 6
        name: expectedDataSetType
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "(xml|excel) # (2)"
        description:
          - lang: ja_JP
            contents: "DataSetの種類を指定します。DataSetとは、RDBのデータ構造を表したもので、DataSetには、CSV、XML、Excelの形式が選べます。本コマンドが利用するDataSetとはすべてDBUnitのDataSetを指します。現状では、CSVには対応ができておりません。"
      - order: 7
        name: actualFlowId
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "結果値を取得したFlowのFlowIDを指定 # (3)"
        description:
          - lang: ja_JP
            contents: "結果値を取得したFlowIDを指定。"
      - order: 8
        name: actualDataSetType
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "(xml|excel) # (4)"
        description:
          - lang: ja_JP
            contents: "DataSetの種類を指定します。DataSetとは、RDBのデータ構造を表したもので、DataSetには、CSV、XML、Excelの形式が選べます。本コマンドが利用するDataSetとはすべてDBUnitのDataSetを指します。現状では、CSVには対応ができておりません。"
      - order: 9
        name: tables
        required: true
        type: array
        summary:
          - lang: ja_JP
            contents: "アサートの詳細設定"
        property:
          - order: 1
            name: table
            required: true
            type: string
            summary:
              - lang: ja_JP
                contents: "対象のテーブル名（物理名）を指定"
          - order: 2
            name: ignoreColumns
            required: true
            type: array
            summary:
              - lang: ja_JP
                contents: "対象のテーブル内でアサートの対象外としたいカラムの指定を行います。"
#####################################
# メッセージ定義
#####################################
messages:
  - id: com.epion_t3.basic.inf.0001
    message:
      - lang: ja_JP
        contents: "指定パターンに合致する文字列が含まれています.指定パターン:{0}"
  - id: com.epion_t3.basic.err.9001
    message:
      - lang: ja_JP
        contents: "参照する変数のスコープが不正です.スコープ:{0}"
  - id: com.epion_t3.basic.err.9002
    message:
      - lang: ja_JP
        contents: "指定パターンに合致する文字列が含まれていません.指定パターン:{0}"
  - id: com.epion_t3.basic.err.9003
    message:
      - lang: ja_JP
        contents: "値（value）は必須です."
  - id: com.epion_t3.basic.err.9004
    message:
      - lang: ja_JP
        contents: "値（value）は数値で指定してください."
  - id: com.epion_t3.basic.err.9005
    message:
      - lang: ja_JP
        contents: "対象（target）は必須です."
  - id: com.epion_t3.basic.err.9006
    message:
      - lang: ja_JP
        contents: "ユーザー入力にてエラーが発生しました."
  - id: com.epion_t3.basic.err.9007
    message:
      - lang: ja_JP
        contents: "対象のファイルが見つかりません.パス：{0}"
  - id: com.epion_t3.basic.err.9008
    message:
      - lang: ja_JP
        contents: "対象のファイルの読み込みに失敗しました.パス：{0}"
  - id: com.epion_t3.basic.err.9009
    message:
      - lang: ja_JP
        contents: "本コマンドはjava.util.Dateを扱うためのコマンドです.変数に格納されているものは型が異なります."
  - id: com.epion_t3.basic.err.9010
    message:
      - lang: ja_JP
        contents: "フォーマット後の格納先変数の指定は必須です."
  - id: com.epion_t3.basic.err.9011
    message:
      - lang: ja_JP
        contents: "日付演算後の格納先変数の指定は必須です."
